### PR TITLE
Add file size to be download.

### PR DESCRIPTION
**Pull request by KevCaz**
Note that this is a PR based on your vcr branch. 

- Add file size of file to be downloaded (when available in header)
- Minor changes in print method and doc. 

Originally I worked on this PR to help you with `vcr`. I've tried to use vcr for the test, but there is something wrong that is somewhat linked with https://github.com/ropensci/crul/issues/150. I would need time to find out what's happening, but I think this is something that needs to be addressed in `vcr`, not here. This should not prevent you from proceeding with the submission, so I would skip most of the tests on CRAN (https://testthat.r-lib.org/articles/skipping.html). 

What I would do though is a vignette and a pkgdown website. Would be happy to help.

### CODE REVIEW

**Comment by VLucet** [comment]
👏🏼 This looks great. I've got to come back to this package asap. Currently juggling a lot of stuff 😅 
Happy to say the pkgdwon website is already up and running! https://vlucet.github.io/rgovcan/ Agree on the vignette, If you can help there this would be greatly appreciated!

**Comment by KevCaz** [comment]
Sorry I've missed the website. I'll do some modif on this PR to remove vcr, and I'll probably create another one for the vignette (do know when, probably this week).

**Comment by KevCaz** [comment]
@VLucet , 

I've changed tibble for dplyr because you're only using `as_tibble()`. TBH, I don't think you need tibble at all, you just need `as.data.frame()` and then you can add the class tibble so that when tibble is loaded, the user would see the data frame formatted as a tibble.  I've used that trick in `govcan_dl_resources.ckan_resource()`: 

```R
out <- structure(as.data.frame(out), class = c("tbl_df", "tbl", "data.frame"))
```

**Comment by VLucet** [comment]
Okay yes that makes complete sense. I really like this new feature, thanks Kevin!

**Pull request merged**
